apply plugin: 'groovy'

repositories {
    google()             // 如果需要依赖 AGP
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'com.android.tools.build:gradle:8.1.4'
    implementation 'com.alibaba:fastjson:1.2.69'
    implementation 'com.squareup:javapoet:1.10.0'
    implementation 'commons-codec:commons-codec:1.10'
    implementation 'commons-io:commons-io:2.4'
}
